server:
  port: 9999
spring:
  application:
    name: excel-screenshot
  #配置邮件属性
  mail:
    host: smtp.office365.com
    port: 587
    username: c2663036501@outlook.com
    password: 1
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            trust: smtp.office365.com
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
#    设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
#    设置链接
    url: jdbc:postgresql://localhost:5432/test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #登录名
    username: postgres
    #密码
    password: root
    #驱动
    driver-class-name: org.postgresql.Driver
  # 开启multipart 邮件上传
  servlet:
    multipart:
      enabled: true
      # 最大上传大小
      max-file-size: 4MB
      # 最大网络传输大小
      max-request-size: 5MB

  thymeleaf:
    #是否开启thymeleaf缓存
    cache: false
    #设置前后缀
    prefix: classpath:/templates/
    #后缀
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html

#生成html页面的目录
html.out.path: scrap

#selenium驱动的位置
selenium.driverClassPath: C:\Program Files\Google\Chrome\Application\chromedriver.exe
#谷歌浏览器的位置
selenium.chromePath: C:\Program Files\Google\Chrome\Application\chrome.exe

mybatis:
  type-aliases-package: quanta.mis.screenshot.pojo
logging:
  level:
    quanta:
      mis:
        screenshot:
          mapper: debug



